default_variable_name_type = "Unique"
default_clock_highlight_type = "Line"
snap_distance = 6
theme = ""
undo_stack_size = 50

[default_time_format]
format = "No"
show_space = true
show_unit = true

[layout]
show_hierarchy = true
show_menu = true
show_toolbar = true
show_ticks = true
show_tooltip = true
show_overview = true
show_statusbar = true
show_variable_indices = true
show_variable_direction = true
window_width = 1920
window_height = 1080
align_names_right = false
hierarchy_style = "Separate"
transactions_line_height = 30.0

[gesture]
style = { color="e9da16", width=2 }
size = 300
deadzone = 20

[behavior]
keep_during_reload = true
arrow_key_bindings = "Edge"
