# VSCode Light+ theme
[theme]
foreground = "343434"
border_color = "282b2d"
canvas_colors = { background = "ffffff", foreground = "343434" }
primary_ui_color = { background = "f3f3f3", foreground = "343434" }
secondary_ui_color = { background = "f3f3f3", foreground = "2c2c2c" }
accent_info = { background = "007acc", foreground = "d4d4d4" }
accent_warn = { background = "32302f", foreground = "d4d4d4" }
accent_error = { background = "32302f", foreground = "d4d4d4" }
signal_default = "1f6102"
signal_undefined = "46000c"
# Convention dictates this being yellow, but yellow is super hard
# to make visible on a white background, so we'll make it Purple
signal_highimp = "46175e"
signal_dontcare = "17265e"
signal_weak = "808080"
cursor = { color="b63935", width=2 }
linewidth = 1.5

[theme.colors]
Green = "6a9955"
Red = "f44747"
Yellow = "ffd602"
Blue = "569cd6"
Pink = "c586c0"
Orange = "ce9178"
Gray = "808080"
Violet = "646695"
